apiVersion: v1
kind: Pod
metadata:
  name: stop-for-nothing
spec:
  containers:
  - name: stop-for-nothing 
    image: my-app
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh","-c","ps aux | grep my-app | kill -9"]